name: Kevin Miller
favicon: null
layout_spectrum: 0.5381157293450087
typography_spectrum: 0.9163927342742682
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.1953129847534001
  lightness: 0.20083410083316267
  saturation: 0.6551916014868766
  rhythmicContrast: 0.19456730876117945
purpose: []
